package jp.ac.kyushu_u.csce.modeltool.base.utility;

import org.eclipse.swt.graphics.RGB;

/**
 * カラーネーム定義クラス<br>
 * @author KBK yoshimura
 */
public interface ColorName {

	/** <font color=#000000><big>■</big></font>black #000000 */
	public static final RGB RGB_BLACK = new RGB(0x00 ,0x00 ,0x00);
	/** <font color=#000080><big>■</big></font>navy #000080 */
	public static final RGB RGB_NAVY = new RGB(0x00 ,0x00 ,0x80);
	/** <font color=#00008b><big>■</big></font>darkblue #00008b */
	public static final RGB RGB_DARKBLUE = new RGB(0x00 ,0x00 ,0x8b);
	/** <font color=#0000cd><big>■</big></font>mediumblue #0000cd */
	public static final RGB RGB_MEDIUMBLUE = new RGB(0x00 ,0x00 ,0xcd);
	/** <font color=#0000ff><big>■</big></font>blue #0000ff */
	public static final RGB RGB_BLUE = new RGB(0x00 ,0x00 ,0xff);
	/** <font color=#006400><big>■</big></font>darkgreen #006400 */
	public static final RGB RGB_DARKGREEN = new RGB(0x00 ,0x64 ,0x00);
	/** <font color=#008000><big>■</big></font>green #008000 */
	public static final RGB RGB_GREEN = new RGB(0x00 ,0x80 ,0x00);
	/** <font color=#008080><big>■</big></font>teal #008080 */
	public static final RGB RGB_TEAL = new RGB(0x00 ,0x80 ,0x80);
	/** <font color=#008b8b><big>■</big></font>darkcyan #008b8b */
	public static final RGB RGB_DARKCYAN = new RGB(0x00 ,0x8b ,0x8b);
	/** <font color=#00bfff><big>■</big></font>deepskyblue #00bfff */
	public static final RGB RGB_DEEPSKYBLUE = new RGB(0x00 ,0xbf ,0xff);
	/** <font color=#00ced1><big>■</big></font>darkturquoise #00ced1 */
	public static final RGB RGB_DARKTURQUOISE = new RGB(0x00 ,0xce ,0xd1);
	/** <font color=#00fa9a><big>■</big></font>mediumspringgreen #00fa9a */
	public static final RGB RGB_MEDIUMSPRINGGREEN = new RGB(0x00 ,0xfa ,0x9a);
	/** <font color=#00ff00><big>■</big></font>lime #00ff00 */
	public static final RGB RGB_LIME = new RGB(0x00 ,0xff ,0x00);
	/** <font color=#00ff7f><big>■</big></font>springgreen #00ff7f */
	public static final RGB RGB_SPRINGGREEN = new RGB(0x00 ,0xff ,0x7f);
	/** <font color=#00ffff><big>■</big></font>aqua #00ffff */
	public static final RGB RGB_AQUA = new RGB(0x00 ,0xff ,0xff);
	/** <font color=#00ffff><big>■</big></font>cyan #00ffff */
	public static final RGB RGB_CYAN = new RGB(0x00 ,0xff ,0xff);
	/** <font color=#191970><big>■</big></font>midnightblue #191970 */
	public static final RGB RGB_MIDNIGHTBLUE = new RGB(0x19 ,0x19 ,0x70);
	/** <font color=#1e90ff><big>■</big></font>dodgerblue #1e90ff */
	public static final RGB RGB_DODGERBLUE = new RGB(0x1e ,0x90 ,0xff);
	/** <font color=#20b2aa><big>■</big></font>lightseagreen #20b2aa */
	public static final RGB RGB_LIGHTSEAGREEN = new RGB(0x20 ,0xb2 ,0xaa);
	/** <font color=#228b22><big>■</big></font>forestgreen #228b22 */
	public static final RGB RGB_FORESTGREEN = new RGB(0x22 ,0x8b ,0x22);
	/** <font color=#2e8b57><big>■</big></font>seagreen #2e8b57 */
	public static final RGB RGB_SEAGREEN = new RGB(0x2e ,0x8b ,0x57);
	/** <font color=#2f4f4f><big>■</big></font>darkslategray #2f4f4f */
	public static final RGB RGB_DARKSLATEGRAY = new RGB(0x2f ,0x4f ,0x4f);
	/** <font color=#32cd32><big>■</big></font>limegreen #32cd32 */
	public static final RGB RGB_LIMEGREEN = new RGB(0x32 ,0xcd ,0x32);
	/** <font color=#3cb371><big>■</big></font>mediumseagreen #3cb371 */
	public static final RGB RGB_MEDIUMSEAGREEN = new RGB(0x3c ,0xb3 ,0x71);
	/** <font color=#40e0d0><big>■</big></font>turquoise #40e0d0 */
	public static final RGB RGB_TURQUOISE = new RGB(0x40 ,0xe0 ,0xd0);
	/** <font color=#4169e1><big>■</big></font>royalblue #4169e1 */
	public static final RGB RGB_ROYALBLUE = new RGB(0x41 ,0x69 ,0xe1);
	/** <font color=#4682b4><big>■</big></font>steelblue #4682b4 */
	public static final RGB RGB_STEELBLUE = new RGB(0x46 ,0x82 ,0xb4);
	/** <font color=#483d8b><big>■</big></font>darkslateblue #483d8b */
	public static final RGB RGB_DARKSLATEBLUE = new RGB(0x48 ,0x3d ,0x8b);
	/** <font color=#48d1cc><big>■</big></font>mediumturquoise #48d1cc */
	public static final RGB RGB_MEDIUMTURQUOISE = new RGB(0x48 ,0xd1 ,0xcc);
	/** <font color=#4b0082><big>■</big></font>indigo #4b0082 */
	public static final RGB RGB_INDIGO = new RGB(0x4b ,0x00 ,0x82);
	/** <font color=#556b2f><big>■</big></font>darkolivegreen #556b2f */
	public static final RGB RGB_DARKOLIVEGREEN = new RGB(0x55 ,0x6b ,0x2f);
	/** <font color=#5f9ea0><big>■</big></font>cadetblue #5f9ea0 */
	public static final RGB RGB_CADETBLUE = new RGB(0x5f ,0x9e ,0xa0);
	/** <font color=#6495ed><big>■</big></font>cornflowerblue #6495ed */
	public static final RGB RGB_CORNFLOWERBLUE = new RGB(0x64 ,0x95 ,0xed);
	/** <font color=#66cdaa><big>■</big></font>mediumaquamarine #66cdaa */
	public static final RGB RGB_MEDIUMAQUAMARINE = new RGB(0x66 ,0xcd ,0xaa);
	/** <font color=#696969><big>■</big></font>dimgray #696969 */
	public static final RGB RGB_DIMGRAY = new RGB(0x69 ,0x69 ,0x69);
	/** <font color=#6a5acd><big>■</big></font>slateblue #6a5acd */
	public static final RGB RGB_SLATEBLUE = new RGB(0x6a ,0x5a ,0xcd);
	/** <font color=#6b8e23><big>■</big></font>olivedrab #6b8e23 */
	public static final RGB RGB_OLIVEDRAB = new RGB(0x6b ,0x8e ,0x23);
	/** <font color=#708090><big>■</big></font>slategray #708090 */
	public static final RGB RGB_SLATEGRAY = new RGB(0x70 ,0x80 ,0x90);
	/** <font color=#778899><big>■</big></font>lightslategray #778899 */
	public static final RGB RGB_LIGHTSLATEGRAY = new RGB(0x77 ,0x88 ,0x99);
	/** <font color=#7b68ee><big>■</big></font>mediumslateblue #7b68ee */
	public static final RGB RGB_MEDIUMSLATEBLUE = new RGB(0x7b ,0x68 ,0xee);
	/** <font color=#7cfc00><big>■</big></font>lawngreen #7cfc00 */
	public static final RGB RGB_LAWNGREEN = new RGB(0x7c ,0xfc ,0x00);
	/** <font color=#7fff00><big>■</big></font>chartreuse #7fff00 */
	public static final RGB RGB_CHARTREUSE = new RGB(0x7f ,0xff ,0x00);
	/** <font color=#7fffd4><big>■</big></font>aquamarine #7fffd4 */
	public static final RGB RGB_AQUAMARINE = new RGB(0x7f ,0xff ,0xd4);
	/** <font color=#800000><big>■</big></font>maroon #800000 */
	public static final RGB RGB_MAROON = new RGB(0x80 ,0x00 ,0x00);
	/** <font color=#800080><big>■</big></font>purple #800080 */
	public static final RGB RGB_PURPLE = new RGB(0x80 ,0x00 ,0x80);
	/** <font color=#808000><big>■</big></font>olive #808000 */
	public static final RGB RGB_OLIVE = new RGB(0x80 ,0x80 ,0x00);
	/** <font color=#808080><big>■</big></font>gray #808080 */
	public static final RGB RGB_GRAY = new RGB(0x80 ,0x80 ,0x80);
	/** <font color=#87ceeb><big>■</big></font>skyblue #87ceeb */
	public static final RGB RGB_SKYBLUE = new RGB(0x87 ,0xce ,0xeb);
	/** <font color=#87cefa><big>■</big></font>lightskyblue #87cefa */
	public static final RGB RGB_LIGHTSKYBLUE = new RGB(0x87 ,0xce ,0xfa);
	/** <font color=#8a2be2><big>■</big></font>blueviolet #8a2be2 */
	public static final RGB RGB_BLUEVIOLET = new RGB(0x8a ,0x2b ,0xe2);
	/** <font color=#8b0000><big>■</big></font>darkred #8b0000 */
	public static final RGB RGB_DARKRED = new RGB(0x8b ,0x00 ,0x00);
	/** <font color=#8b008b><big>■</big></font>darkmagenta #8b008b */
	public static final RGB RGB_DARKMAGENTA = new RGB(0x8b ,0x00 ,0x8b);
	/** <font color=#8b4513><big>■</big></font>saddlebrown #8b4513 */
	public static final RGB RGB_SADDLEBROWN = new RGB(0x8b ,0x45 ,0x13);
	/** <font color=#8fbc8f><big>■</big></font>darkseagreen #8fbc8f */
	public static final RGB RGB_DARKSEAGREEN = new RGB(0x8f ,0xbc ,0x8f);
	/** <font color=#90ee90><big>■</big></font>lightgreen #90ee90 */
	public static final RGB RGB_LIGHTGREEN = new RGB(0x90 ,0xee ,0x90);
	/** <font color=#9370db><big>■</big></font>mediumpurple #9370db */
	public static final RGB RGB_MEDIUMPURPLE = new RGB(0x93 ,0x70 ,0xdb);
	/** <font color=#9400d3><big>■</big></font>darkviolet #9400d3 */
	public static final RGB RGB_DARKVIOLET = new RGB(0x94 ,0x00 ,0xd3);
	/** <font color=#98fb98><big>■</big></font>palegreen #98fb98 */
	public static final RGB RGB_PALEGREEN = new RGB(0x98 ,0xfb ,0x98);
	/** <font color=#9932cc><big>■</big></font>darkorchid #9932cc */
	public static final RGB RGB_DARKORCHID = new RGB(0x99 ,0x32 ,0xcc);
	/** <font color=#9acd32><big>■</big></font>yellowgreen #9acd32 */
	public static final RGB RGB_YELLOWGREEN = new RGB(0x9a ,0xcd ,0x32);
	/** <font color=#a0522d><big>■</big></font>sienna #a0522d */
	public static final RGB RGB_SIENNA = new RGB(0xa0 ,0x52 ,0x2d);
	/** <font color=#a52a2a><big>■</big></font>brown #a52a2a */
	public static final RGB RGB_BROWN = new RGB(0xa5 ,0x2a ,0x2a);
	/** <font color=#a9a9a9><big>■</big></font>darkgray #a9a9a9 */
	public static final RGB RGB_DARKGRAY = new RGB(0xa9 ,0xa9 ,0xa9);
	/** <font color=#add8e6><big>■</big></font>lightblue #add8e6 */
	public static final RGB RGB_LIGHTBLUE = new RGB(0xad ,0xd8 ,0xe6);
	/** <font color=#adff2f><big>■</big></font>greenyellow #adff2f */
	public static final RGB RGB_GREENYELLOW = new RGB(0xad ,0xff ,0x2f);
	/** <font color=#afeeee><big>■</big></font>paleturquoise #afeeee */
	public static final RGB RGB_PALETURQUOISE = new RGB(0xaf ,0xee ,0xee);
	/** <font color=#b0c4de><big>■</big></font>lightsteelblue #b0c4de */
	public static final RGB RGB_LIGHTSTEELBLUE = new RGB(0xb0 ,0xc4 ,0xde);
	/** <font color=#b0e0e6><big>■</big></font>powderblue #b0e0e6 */
	public static final RGB RGB_POWDERBLUE = new RGB(0xb0 ,0xe0 ,0xe6);
	/** <font color=#b22222><big>■</big></font>firebrick #b22222 */
	public static final RGB RGB_FIREBRICK = new RGB(0xb2 ,0x22 ,0x22);
	/** <font color=#b8860b><big>■</big></font>darkgoldenrod #b8860b */
	public static final RGB RGB_DARKGOLDENROD = new RGB(0xb8 ,0x86 ,0x0b);
	/** <font color=#ba55d3><big>■</big></font>mediumorchid #ba55d3 */
	public static final RGB RGB_MEDIUMORCHID = new RGB(0xba ,0x55 ,0xd3);
	/** <font color=#bc8f8f><big>■</big></font>rosybrown #bc8f8f */
	public static final RGB RGB_ROSYBROWN = new RGB(0xbc ,0x8f ,0x8f);
	/** <font color=#bdb76b><big>■</big></font>darkkhaki #bdb76b */
	public static final RGB RGB_DARKKHAKI = new RGB(0xbd ,0xb7 ,0x6b);
	/** <font color=#c0c0c0><big>■</big></font>silver #c0c0c0 */
	public static final RGB RGB_SILVER = new RGB(0xc0 ,0xc0 ,0xc0);
	/** <font color=#c71585><big>■</big></font>mediumvioletred #c71585 */
	public static final RGB RGB_MEDIUMVIOLETRED = new RGB(0xc7 ,0x15 ,0x85);
	/** <font color=#cd5c5c><big>■</big></font>indianred #cd5c5c */
	public static final RGB RGB_INDIANRED = new RGB(0xcd ,0x5c ,0x5c);
	/** <font color=#cd853f><big>■</big></font>peru #cd853f */
	public static final RGB RGB_PERU = new RGB(0xcd ,0x85 ,0x3f);
	/** <font color=#d2691e><big>■</big></font>chocolate #d2691e */
	public static final RGB RGB_CHOCOLATE = new RGB(0xd2 ,0x69 ,0x1e);
	/** <font color=#d2b48c><big>■</big></font>tan #d2b48c */
	public static final RGB RGB_TAN = new RGB(0xd2 ,0xb4 ,0x8c);
	/** <font color=#d3d3d3><big>■</big></font>lightgrey #d3d3d3 */
	public static final RGB RGB_LIGHTGREY = new RGB(0xd3 ,0xd3 ,0xd3);
	/** <font color=#d8bfd8><big>■</big></font>thistle #d8bfd8 */
	public static final RGB RGB_THISTLE = new RGB(0xd8 ,0xbf ,0xd8);
	/** <font color=#da70d6><big>■</big></font>orchid #da70d6 */
	public static final RGB RGB_ORCHID = new RGB(0xda ,0x70 ,0xd6);
	/** <font color=#daa520><big>■</big></font>goldenrod #daa520 */
	public static final RGB RGB_GOLDENROD = new RGB(0xda ,0xa5 ,0x20);
	/** <font color=#db7093><big>■</big></font>vpalevioletred #db7093 */
	public static final RGB RGB_VPALEVIOLETRED = new RGB(0xdb ,0x70 ,0x93);
	/** <font color=#dc143c><big>■</big></font>crimson #dc143c */
	public static final RGB RGB_CRIMSON = new RGB(0xdc ,0x14 ,0x3c);
	/** <font color=#dcdcdc><big>■</big></font>gainsboro #dcdcdc */
	public static final RGB RGB_GAINSBORO = new RGB(0xdc ,0xdc ,0xdc);
	/** <font color=#dda0dd><big>■</big></font>plum #dda0dd */
	public static final RGB RGB_PLUM = new RGB(0xdd ,0xa0 ,0xdd);
	/** <font color=#deb887><big>■</big></font>burlywood #deb887 */
	public static final RGB RGB_BURLYWOOD = new RGB(0xde ,0xb8 ,0x87);
	/** <font color=#e0ffff><big>■</big></font>lightcyan #e0ffff */
	public static final RGB RGB_LIGHTCYAN = new RGB(0xe0 ,0xff ,0xff);
	/** <font color=#e6e6fa><big>■</big></font>lavender #e6e6fa */
	public static final RGB RGB_LAVENDER = new RGB(0xe6 ,0xe6 ,0xfa);
	/** <font color=#e9967a><big>■</big></font>darksalmon #e9967a */
	public static final RGB RGB_DARKSALMON = new RGB(0xe9 ,0x96 ,0x7a);
	/** <font color=#ee82ee><big>■</big></font>violet #ee82ee */
	public static final RGB RGB_VIOLET = new RGB(0xee ,0x82 ,0xee);
	/** <font color=#eee8aa><big>■</big></font>palegoldenrod #eee8aa */
	public static final RGB RGB_PALEGOLDENROD = new RGB(0xee ,0xe8 ,0xaa);
	/** <font color=#f08080><big>■</big></font>lightcoral #f08080 */
	public static final RGB RGB_LIGHTCORAL = new RGB(0xf0 ,0x80 ,0x80);
	/** <font color=#f0e68c><big>■</big></font>khaki #f0e68c */
	public static final RGB RGB_KHAKI = new RGB(0xf0 ,0xe6 ,0x8c);
	/** <font color=#f0f8ff><big>■</big></font>aliceblue #f0f8ff */
	public static final RGB RGB_ALICEBLUE = new RGB(0xf0 ,0xf8 ,0xff);
	/** <font color=#f0fff0><big>■</big></font>honeydew #f0fff0 */
	public static final RGB RGB_HONEYDEW = new RGB(0xf0 ,0xff ,0xf0);
	/** <font color=#f0ffff><big>■</big></font>azure #f0ffff */
	public static final RGB RGB_AZURE = new RGB(0xf0 ,0xff ,0xff);
	/** <font color=#f4a460><big>■</big></font>sandybrown #f4a460 */
	public static final RGB RGB_SANDYBROWN = new RGB(0xf4 ,0xa4 ,0x60);
	/** <font color=#f5deb3><big>■</big></font>wheat #f5deb3 */
	public static final RGB RGB_WHEAT = new RGB(0xf5 ,0xde ,0xb3);
	/** <font color=#f5f5dc><big>■</big></font>beige #f5f5dc */
	public static final RGB RGB_BEIGE = new RGB(0xf5 ,0xf5 ,0xdc);
	/** <font color=#f5f5f5><big>■</big></font>whitesmoke #f5f5f5 */
	public static final RGB RGB_WHITESMOKE = new RGB(0xf5 ,0xf5 ,0xf5);
	/** <font color=#f5fffa><big>■</big></font>mintcream #f5fffa */
	public static final RGB RGB_MINTCREAM = new RGB(0xf5 ,0xff ,0xfa);
	/** <font color=#f8f8ff><big>■</big></font>ghostwhite #f8f8ff */
	public static final RGB RGB_GHOSTWHITE = new RGB(0xf8 ,0xf8 ,0xff);
	/** <font color=#fa8072><big>■</big></font>salmon #fa8072 */
	public static final RGB RGB_SALMON = new RGB(0xfa ,0x80 ,0x72);
	/** <font color=#faebd7><big>■</big></font>antiquewhite #faebd7 */
	public static final RGB RGB_ANTIQUEWHITE = new RGB(0xfa ,0xeb ,0xd7);
	/** <font color=#faf0e6><big>■</big></font>linen #faf0e6 */
	public static final RGB RGB_LINEN = new RGB(0xfa ,0xf0 ,0xe6);
	/** <font color=#fafad2><big>■</big></font>lightgoldenrodyellow #fafad2 */
	public static final RGB RGB_LIGHTGOLDENRODYELLOW = new RGB(0xfa ,0xfa ,0xd2);
	/** <font color=#fdf5e6><big>■</big></font>oldlace #fdf5e6 */
	public static final RGB RGB_OLDLACE = new RGB(0xfd ,0xf5 ,0xe6);
	/** <font color=#ff0000><big>■</big></font>red #ff0000 */
	public static final RGB RGB_RED = new RGB(0xff ,0x00 ,0x00);
	/** <font color=#ff00ff><big>■</big></font>fuchsia #ff00ff */
	public static final RGB RGB_FUCHSIA = new RGB(0xff ,0x00 ,0xff);
	/** <font color=#ff00ff><big>■</big></font>magenta #ff00ff */
	public static final RGB RGB_MAGENTA = new RGB(0xff ,0x00 ,0xff);
	/** <font color=#ff1493><big>■</big></font>deeppink #ff1493 */
	public static final RGB RGB_DEEPPINK = new RGB(0xff ,0x14 ,0x93);
	/** <font color=#ff4500><big>■</big></font>orangered #ff4500 */
	public static final RGB RGB_ORANGERED = new RGB(0xff ,0x45 ,0x00);
	/** <font color=#ff6347><big>■</big></font>tomato #ff6347 */
	public static final RGB RGB_TOMATO = new RGB(0xff ,0x63 ,0x47);
	/** <font color=#ff69b4><big>■</big></font>hotpink #ff69b4 */
	public static final RGB RGB_HOTPINK = new RGB(0xff ,0x69 ,0xb4);
	/** <font color=#ff7f50><big>■</big></font>coral #ff7f50 */
	public static final RGB RGB_CORAL = new RGB(0xff ,0x7f ,0x50);
	/** <font color=#ff8c00><big>■</big></font>darkorange #ff8c00 */
	public static final RGB RGB_DARKORANGE = new RGB(0xff ,0x8c ,0x00);
	/** <font color=#ffa07a><big>■</big></font>lightsalmon #ffa07a */
	public static final RGB RGB_LIGHTSALMON = new RGB(0xff ,0xa0 ,0x7a);
	/** <font color=#ffa500><big>■</big></font>orange #ffa500 */
	public static final RGB RGB_ORANGE = new RGB(0xff ,0xa5 ,0x00);
	/** <font color=#ffb6c1><big>■</big></font>lightpink #ffb6c1 */
	public static final RGB RGB_LIGHTPINK = new RGB(0xff ,0xb6 ,0xc1);
	/** <font color=#ffc0cb><big>■</big></font>pink #ffc0cb */
	public static final RGB RGB_PINK = new RGB(0xff ,0xc0 ,0xcb);
	/** <font color=#ffd700><big>■</big></font>gold #ffd700 */
	public static final RGB RGB_GOLD = new RGB(0xff ,0xd7 ,0x00);
	/** <font color=#ffdab9><big>■</big></font>peachpuff #ffdab9 */
	public static final RGB RGB_PEACHPUFF = new RGB(0xff ,0xda ,0xb9);
	/** <font color=#ffdead><big>■</big></font>navajowhite #ffdead */
	public static final RGB RGB_NAVAJOWHITE = new RGB(0xff ,0xde ,0xad);
	/** <font color=#ffe4b5><big>■</big></font>moccasin #ffe4b5 */
	public static final RGB RGB_MOCCASIN = new RGB(0xff ,0xe4 ,0xb5);
	/** <font color=#ffe4c4><big>■</big></font>bisque #ffe4c4 */
	public static final RGB RGB_BISQUE = new RGB(0xff ,0xe4 ,0xc4);
	/** <font color=#ffe4e1><big>■</big></font>mistyrose #ffe4e1 */
	public static final RGB RGB_MISTYROSE = new RGB(0xff ,0xe4 ,0xe1);
	/** <font color=#ffebcd><big>■</big></font>blanchedalmond #ffebcd */
	public static final RGB RGB_BLANCHEDALMOND = new RGB(0xff ,0xeb ,0xcd);
	/** <font color=#ffefd5><big>■</big></font>papayawhip #ffefd5 */
	public static final RGB RGB_PAPAYAWHIP = new RGB(0xff ,0xef ,0xd5);
	/** <font color=#fff0f5><big>■</big></font>lavenderblush #fff0f5 */
	public static final RGB RGB_LAVENDERBLUSH = new RGB(0xff ,0xf0 ,0xf5);
	/** <font color=#fff5ee><big>■</big></font>seashell #fff5ee */
	public static final RGB RGB_SEASHELL = new RGB(0xff ,0xf5 ,0xee);
	/** <font color=#fff8dc><big>■</big></font>cornsilk #fff8dc */
	public static final RGB RGB_CORNSILK = new RGB(0xff ,0xf8 ,0xdc);
	/** <font color=#fffacd><big>■</big></font>lemonchiffon #fffacd */
	public static final RGB RGB_LEMONCHIFFON = new RGB(0xff ,0xfa ,0xcd);
	/** <font color=#fffaf0><big>■</big></font>floralwhite #fffaf0 */
	public static final RGB RGB_FLORALWHITE = new RGB(0xff ,0xfa ,0xf0);
	/** <font color=#fffafa><big>■</big></font>snow #fffafa */
	public static final RGB RGB_SNOW = new RGB(0xff ,0xfa ,0xfa);
	/** <font color=#ffff00><big>■</big></font>yellow #ffff00 */
	public static final RGB RGB_YELLOW = new RGB(0xff ,0xff ,0x00);
	/** <font color=#ffffe0><big>■</big></font>lightyellow #ffffe0 */
	public static final RGB RGB_LIGHTYELLOW = new RGB(0xff ,0xff ,0xe0);
	/** <font color=#fffff0><big>■</big></font>ivory #fffff0 */
	public static final RGB RGB_IVORY = new RGB(0xff ,0xff ,0xf0);
	/** <font color=#ffffff><big>■</big></font>white #ffffff */
	public static final RGB RGB_WHITE = new RGB(0xff ,0xff ,0xff);

}
